config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, :content, presence: true
  validates :rating, inclusion: { in: (0..5) }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[edit update show]
  def index
    params[:query]? @restaurants = Restaurant.where("name LIKE '%#{params[:query]}%'") : @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end
  
  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit restaurant</h1>
  <%= form_with model: @restaurant, class: "form-group" do |f| %>
    <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :category %>
      <%= f.text_field :category, class: "form-control" %>
    </div>
    <div>
     <%= f.submit 'Edit', class: "btn btn-primary text-decoration-none mt-3" %>
    </div>
  <% end %>
  <%= link_to 'Return to the main menu', restaurants_path, class: "btn btn-info text-decoration-none mt-4" %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <fieldset>
    <h1 class="mb-3">Restaurants</h1>
    <form action="/restaurants" method="get">
      <div class="form-group d-flex mb-3">
        <input type="search" name="query" class="form-control" placeholder="Search a restaurant">
        <button type="submit" class="btn btn-success">Search</button>
      </div>
    </form>
    <%= link_to 'Create new restaurant', new_restaurant_path, class: "btn btn-primary text-decoration-none mb-3" %>
  </fieldset>
</div>
<div class="container">
  <div class="cards">
  <% @restaurants.reverse.each do |restaurant| %>
      <div class="card">
        <img src="" alt="restaurant-image">
        <%= link_to restaurant.name, restaurant_path(restaurant.id), class: "alert alert-info text-decoration-none mt-2" %>
        <%= restaurant.address %>
      </div>
  <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New restaurant</h1>
  <%= form_with model: @restaurant, class: "form-group" do |f| %>
    <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :category %>
      <%= f.text_field :category, class: "form-control" %>
    </div>
    <div>
     <%= f.submit 'Create', class: "btn btn-primary text-decoration-none mt-3" %>
    </div>
  <% end %>
  <%= link_to 'Return to the main menu', restaurants_path, class: "btn btn-info text-decoration-none mt-4" %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name.capitalize %></h2>
  <div class="address">
    <p>Address: <%= @restaurant.address %></p>
  </div>
  <div class="phone_number">
    <p>Phone number: <%= @restaurant.phone_number %></p>
  </div>
  <div class="category">
    <p>Category: <%= @restaurant.category %></p>
  </div>
  <div>
  <%= link_to 'Give a review restaurant', new_restaurant_review_path(@restaurant), class: "btn btn-info text-decoration-none"  %>
  <%= link_to 'Edit restaurant', edit_restaurant_path, class: "btn btn-warning text-decoration-none"  %>
  <%= link_to "Delete restaurant", restaurant_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger text-decoration-none"  %>
  </div>
  <%= link_to 'Return to the main menu', restaurants_path, class: "btn btn-info text-decoration-none mt-4 mb-3" %>
  <h2>Reviews</h2>
  <ul class="list-group d-flex">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">
      <%= review.content %>
       ------------- Rating:
       <%= review.rating %>
       <%= link_to "Delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
       </li>
    <% end %>
  </ul>
  <br>
</div>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New review for "<%= @restaurant.name %>"</h1>
  <%= simple_form_for [@restaurant, @review], class: "form-group" do |f| %>
    <div class="mb-3">
      <%= f.label :rating %>
      <%= f.text_field :rating, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :content %>
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <div>
     <%= f.submit 'Submit review', class: "btn btn-primary text-decoration-none mt-3" %>
    </div>
  <% end %>
  <%= link_to 'Return to the main menu', restaurants_path, class: "btn btn-info text-decoration-none mt-4" %>
</div>